### PR TITLE
update cdn-links

### PR DESCRIPTION
**Pull request by devpanda0**

### CODE REVIEW

**Review by shloooo — APPROVED** [review]
looks good

**Comment by mrgharabaghi** [comment]
@shloooo 
> At least 2 approving reviews are required by reviewers with write access.

**Comment by shloooo** [comment]
> @shloooo
> 
> > At least 2 approving reviews are required by reviewers with write access.

Who the fuck cares ?

**Comment by mrgharabaghi** [comment]
Is there a specific reason you don't approve this?

**Comment by devpanda0** [comment]
> Is there a specific reason you don't approve this?

¯\_(ツ)_/¯

**Comment by shloooo** [comment]
Screenshot_20241028_153928_com android chrome_edit_1195199452212415
?

**Pull request merged**
